getwd()
rm(list = ls() )
captaincyOne = read.csv("CaptaincyData.csv")
View(captaincyOne)
summary(captaincyOne)
class(captaincyOne)
typeof(captaincyOne)
help(typeof)
head(captaincyOne,2)
tail(captaincyOne,2)
str(captaincyOne)
captaincyTwo <- read.csv("CaptaincyData2.csv")
View(captaincyTwo)
#merging 2 files
captaincyOne <- merge(captaincyOne,captaincyTwo,
                      by = "names")
View(captaincyOne)
#importing data in diff formats
library()
install.packages("XML")
library("XML")
xmldata <- xmlToDataFrame("CaptaincyData.xml")
View(xmldata)
txtdata <- read.table("CaptaincyData.txt")
View(txtdata)
install.packages("readxl")
library("readxl")
library("Rcpp")
